POST http://localhost:3000/api/user/register HTTP/1.1
content-type: application/json

{
    "name": "sample name",
    "email": "abcd1234@testproject.com",
    "password": "1234567"
}

###

POST http://localhost:3000/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "abcd1234@testproject.com",
    "password": "1234567"
}

###

GET http://localhost:3000/api/posts HTTP/1.1
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDRhZjIwMGI1ZjAzMTcyNjUzNzY2Y2QiLCJpYXQiOjE2MTU1MzE5MDR9.rjoVOLjCaQZte5VDYdCSzenUTex6H85Rp8DgUistYfQ